# Objective
Understand the basics of Python and use the Pandas library to perform data exploration and cleaning on an e-commerce dataset.
## Steps Covered:
1. Import and load a CSV dataset into a Pandas DataFrame
2. Explore the dataset using functions like head(), tail(), shape, columns, and data types
3. Detect and handle missing values using fill and drop operations
4. Apply basic data operations such as filtering rows and selecting columns
5. Identify and remove duplicate records
6. Generate new derived columns from existing data
7. Export the cleaned dataset into a new CSV file

# Step 1: Import Libraries

In [2]:
import pandas as pd
import numpy as np
import warnings

#used for cleaner output
warnings.filterwarnings('ignore')

print('Libraries imported successfully!')

Libraries imported successfully!

# Step 2: Load the Dataset

In [3]:
# Load data into a DataFrame
df = pd.read_csv('Shopping.csv')

print('Dataset loaded successfully!')

Dataset loaded successfully!

# Step 3: Data Exploration

## Basic Information

In [4]:
print("First 5 rows of the dataset")
df.head()

First 5 rows of the dataset

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [5]:
print("Last 5 rows of the dataset")
df.tail()

Last 5 rows of the dataset

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [6]:
print(f"Dataset Shape: {df.shape}")
print(f"Total Rows : {df.shape[0]}")
print(f"Total Columns : {df.shape[1]}")

Dataset Shape: (1000, 24)
Total Rows : 1000
Total Columns : 24

## Column Inforamtion of Dataset

In [7]:
print("The columns in the Dataset are:")
print(np.array(df.columns))

The columns in the Dataset are:
['product_id' 'title' 'product_description' 'rating' 'ratings_count'
 'initial_price' 'discount' 'final_price' 'currency' 'images'
 'delivery_options' 'product_details' 'breadcrumbs'
 'product_specifications' 'amount_of_stars' 'what_customers_said'
 'seller_name' 'sizes' 'videos' 'seller_information' 'variations'
 'best_offer' 'more_offers' 'category']

# Data Types

In [8]:
print("Data Types")
pd.DataFrame({"Column Name" : df.columns , "Data Types" : df.dtypes.values})

Data Types

               Column Name Data Types
0               product_id      int64
1                    title     object
2      product_description     object
3                   rating    float64
4            ratings_count      int64
5            initial_price      int64
6                 discount    float64
7              final_price     object
8                 currency     object
9                   images     object
10        delivery_options     object
11         product_details     object
12             breadcrumbs     object
13  product_specifications     object
14         amount_of_stars     object
15     what_customers_said     object
16             seller_name     object
17                   sizes     object
18                  videos     object
19      seller_information     object
20              variations     object
21              best_offer     object
22             more_offers     object
23                category     object

In [9]:
print("General information about the Dataset")
df.info()

General information about the Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

## Statistical Summary

In [10]:
print("Discription of Dataset ")
df.describe()

Discription of Dataset

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

# Step 4: Handle Missing Values

# 4.1 Identify Missing Values

In [26]:
missing_values = df.isnull().sum()
missing_df = pd.DataFrame({
    'Column': missing_values.index,
    'Missing_Count': missing_values.values
})
missing_df = missing_df[missing_df['Missing_Count'] > 0].sort_values('Missing_Count',ascending = False)
print('Printing Missing Values:')
missing_df

Printing Missing Values:

                 Column  Missing_Count
18               videos            781
15  what_customers_said            573
20           variations            562
16          seller_name            301
19   seller_information            301
6              discount            121

 # 4.2 Handling Missing Values

In [30]:
# Fill missing values in numerical columns with median
for col in df.select_dtypes(include=['int64', 'float64']):
    df[col].fillna(df[col].median(), inplace=True)

# Fill missing values in categorical columns with mode
for col in df.select_dtypes(include='object'):
    df[col].fillna(df[col].mode()[0], inplace=True)

# Check remaining missing values
print(df.isnull().sum().sum())

0

# Step 5: Filtering

In [32]:
# Select specific columns
important_cols = ['product_id', 'title', 'category', 'initial_price', 'discount', 'rating', 'ratings_count']
df_selected = df[important_cols].copy()

print(df_selected.head(5))

   product_id           title   category  initial_price  discount  rating  \
0     8376765     Lino Perros  backpacks           3995      58.0     3.8
1     9136281  Tommy Hilfiger  backpacks           2899      35.0     4.5
2    17633752           Lavie  backpacks           2999      65.0     4.4
3     1376949          F Gear  backpacks           1675      52.0     4.4
4    13939916       MYTRIDENT  bath-robe           2899      17.0     4.7

   ratings_count
0             15
1             67
2            226
3           1052
4             12

In [34]:
# Filter products with high ratings
high_rated = df[df['rating'] >= 4.0]
print(f'Products with rating >= 4.0: {len(high_rated)} out of {len(df)}')

print('\nSample of high-rated products:')
print(high_rated[['title', 'rating', 'ratings_count']].head(10))

Products with rating >= 4.0: 615 out of 1000

Sample of high-rated products:
             title  rating  ratings_count
1   Tommy Hilfiger     4.5             67
2            Lavie     4.4            226
3           F Gear     4.4           1052
4        MYTRIDENT     4.7             12
5              H&M     4.5             42
6       AVI Living     4.0              5
7          My Room     4.7             10
8          My Room     4.5             22
10       MYTRIDENT     4.4             26
15    Home Ecstasy     4.5              6

In [35]:
# Filter products with significant discounts (>50%)
high_discount = df[df['discount'] > 50]
print(f'Products with discount > 50%: {len(high_discount)} out of {len(df)}')

print('\nSample of high-discount products:')
print(high_discount[['title', 'initial_price', 'discount']].head(10))

Products with discount > 50%: 644 out of 1000

Sample of high-discount products:
          title  initial_price  discount
0   Lino Perros           3995      58.0
2         Lavie           2999      65.0
3        F Gear           1675      52.0
5           H&M           1399      56.0
6    AVI Living           1399      65.0
7       My Room           2999      54.0
8       My Room           2999      54.0
9    Story@home           2199      53.0
11       Arrabi           3329      74.0
12   BELLA CASA           1499      73.0

# Step 6: Remove Duplicates

In [36]:
# Check for duplicates
print(f'Total rows before removing duplicates: {len(df)}')
print(f'Duplicate rows based on product_id: {df.duplicated(subset=["product_id"]).sum()}')

# Remove duplicates
df = df.drop_duplicates(subset=['product_id'], keep='first')
print(f'Total rows after removing duplicates: {len(df)}')

Total rows before removing duplicates: 1000
Duplicate rows based on product_id: 0
Total rows after removing duplicates: 1000

# Step 7: Create Derived Columns

In [40]:
# Create a derived column: discount_amount (savings in rupees)
df['discount_amount'] = (df['initial_price'] * df['discount']) / 100

# Create a column: final_price (calculated from initial_price and discount)
df['final_price_calculated'] = df['initial_price'] - df['discount_amount']

# Create a quality score based on rating and number of ratings
df['quality_score'] = (df['rating'] * df['ratings_count']) / df['ratings_count'].max()

print('\nSample of new columns:')
print(df[['title', 'initial_price', 'discount', 'discount_amount', 'final_price_calculated']].head(10))

Sample of new columns:
            title  initial_price  discount  discount_amount  \
0     Lino Perros           3995      58.0          2317.10
1  Tommy Hilfiger           2899      35.0          1014.65
2           Lavie           2999      65.0          1949.35
3          F Gear           1675      52.0           871.00
4       MYTRIDENT           2899      17.0           492.83
5             H&M           1399      56.0           783.44
6      AVI Living           1399      65.0           909.35
7         My Room           2999      54.0          1619.46
8         My Room           2999      54.0          1619.46
9      Story@home           2199      53.0          1165.47

   final_price_calculated
0                 1677.90
1                 1884.35
2                 1049.65
3                  804.00
4                 2406.17
5                  615.56
6                  489.65
7                 1379.54
8                 1379.54
9                 1033.53

# Step 8: Final Data Validation

In [41]:
# Validate data quality
print('Final Data Validation:')
print(f'Total rows: {len(df)}')
print(f'Total columns: {len(df.columns)}')
print(f'Missing values: {df.isnull().sum().sum()}')
print(f'Duplicate rows: {df.duplicated().sum()}')
print(f'\nData quality: PASSED ✓')

Final Data Validation:
Total rows: 1000
Total columns: 27
Missing values: 0
Duplicate rows: 0

Data quality: PASSED ✓

# Step 9: Save Cleaned Dataset

In [42]:
# Save cleaned dataset
output_file = 'Combined_dataset_CLEANED.csv'
df.to_csv(output_file, index=False)